### ISSUE TITLE
Fix 'qualifiedName' field in 'AbstractVariable' class.

### ISSUE THREAD

**Issue by lyubortk** [ml-in-programming/IntelliJDeodorant#6]
`qualifiedName` field contains the text of variable declaration which is not unique and might not even exist (e.g. for fields generated by [Lombok plugin](https://github.com/mplushnikov/lombok-intellij-plugin))

**Comment by onewhl** [comment]
The issue was resolved: https://github.com/ml-in-programming/IntelliJDeodorant/pull/7
